blank_issues_enabled: true
contact_links:
  - name: Discord Community
    url: https://discord.gg/kTQ5KWANp8
    about: Join our Discord Community for Disucussion
  - name: LinkedIn Page
    url: https://www.linkedin.com/company/wallgodds/posts/?feedView=all
    about: Follow us on our LinkedIn Page
